### ISSUE TITLE
Correcion

### ISSUE THREAD

**Issue by GOrellanoGL** [GonzaRom/Romero-Gonzalo---TP-1---COM-4#1]
Gonza: 

Te dejo por acá la corrección sobre el tp.

- El método  createDrawing podría ser un void y dentro tener un SOUT. Lo mismo pasa con el método de la interface.

- Los atributos de las clases son siempre private salvo en algunos casos en que van a ser de tipo protected. Por los hiciste de esta forma?

- Bien el uso de interface (tene cuidado que en las interfaces solo son cabeceras de métodos, no hay implementacion ni atributos, la edad esta mal que este en la interface este puede ser un atributo de la clase MaestroMayorDeObra o de Obrero) . 

- Esta perfecto tener un constructor vacío, es una buena practica esto. Bien el uso de la clase abstracta.

- Bien el uso de ArrayList (tambien podes usar List). Bien el uso de forEach. Fíjate el tema de las comparaciones que haces countArch == 1, se podría implementar el uso de equals. Muy bien las validaciones.

- Esta muy bien el tp.

**Comment by GonzaRom** [comment]
Con respecto a lo que me marcabas, en el punto del metodo createDrawing lo plantie que fuera un String para evitar usar el SOUT directamente desde un metodo dentro de una clase, (me quedo eso de lo que estuvimos hablando en clase). 

> Los atributos de las clases son siempre private salvo en algunos casos en que van a ser de tipo protected. Por los hiciste de esta forma?

`public class Comercial extends ConstructionSite {`
   ` private String typeOfBusiness;`
  `  protected String name;`

En este caso lo use porque Hotel hereda de la clase Comercial y el  Hotel no usa el parametro typeOfBusiness pero si name, por eso lo puse privado para que no lo heredara. No se si es la manera correcta,,,

Gracias por el feedback!
